# Generated by Django 3.2.7 on 2021-09-05 18:34

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
