# Generated by Django 3.2.7 on 2021-09-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20210912_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='details',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
