# Generated by Django 3.2.7 on 2023-10-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_technology_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
    ]
