# Generated by Django 3.2.7 on 2023-10-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_technology_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='content.Technology'),
        ),
        migrations.AlterField(
            model_name='about',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(),
        ),
    ]
